name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20, 21]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Updated to v3

      - name: Cache Node.js modules
        uses: actions/cache@v3 # Updated to v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          mkdir -p test-results  # Ensure the directory exists
          npx jest --ci --coverage

      - name: List test results
        run: ls -la test-results # List the contents of the directory

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3 # Updated to v3
        with:
          name: test-results
          path: test-results/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1 # Add Codecov action
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Clean up
        run: rm -rf node_modules
